### ISSUE TITLE
OVN LB failed to create

### ISSUE THREAD

**Issue by mathgonzlez** [stackhpc/magnum-capi-helm#54]
Hi,
I trying to expose a service using OVN as backend for octavia but im not able to change the provider from 'amphora' to 'ovn'

`2024-03-20 01:41:03.847 24 WARNING octavia.api.drivers.driver_factory [None req-c0011348-0b65-4d6a-b1ba-f4db8565fbaf - 01adb0aae1b94bd493311c94456643a4 - - default default] Requested provider driver 'amphora' was not enabled in the configuration file.`

i user the label 'octavia_provider=ovn' in the 'coe template' and in the 'cluster creation' but nothing works.

**Comment by sd109** [comment]
Hi,

I think this label is specifying which load balancer type should be used for the Kubernetes API server on your cluster, which is different from the LB type which should be used for services within the cluster. Although it probably makes sense for us to use the same type for both.

You can check which load balancer type is configured for cluster services by looking at the Helm values for the installed `openstack-cloud-controller-manager` chart on your cluster. I think there should be a value named `lb-provider` and this will probably be set to amphora because this is what the upstream OpenStack controller manager does (see [these docs](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#config-openstack-cloud-controller-manager)).

I will make a note of this and propose a fix so that the cluster label affects both values.

**Comment by sd109** [comment]
I've now proposed a fix for this here: https://review.opendev.org/c/openstack/magnum-capi-helm/+/915473
